apiVersion: v1
kind: Service
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  ports:
    - name: http
      port: 8080
      targetPort: 8080
  selector:
    app: keycloak
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: keycloak
  labels:
    app: keycloak
spec:
  replicas: 1
  selector:
    matchLabels:
      app: keycloak
  template:
    metadata:
      labels:
        app: keycloak
    spec:
      securityContext:
        runAsUser: 1000
      containers:
        - name: keycloak
          image: sandeeplv/keycloak:v1
          args: ["start", "--cache-stack=kubernetes", "--spi-login-protocol-openid-connect-legacy-logout-redirect-uri=true", "--https-certificate-file=/opt/keycloak-ingress-tls-cert.pem", "--https-certificate-key-file=/opt/keycloak-ingress-tls-key.pem"]
          env:
            - name: KEYCLOAK_ADMIN
              value: "admin"
            - name: KEYCLOAK_ADMIN_PASSWORD
              value: "password"
            - name: KC_PROXY
              value: "edge"
            - name: jgroups.dns.query
              value: "keycloak"
            - name: PROXY_ADDRESS_FORWARDING
              value: "true"
            - name: KC_HEALTH_ENABLED
              value: "true"
            - name: KC_METRICS_ENABLED
              value: "true"
            - name: KC_HTTP_ENABLED
              value: "false"
            - name: KC_HTTP_RELATIVE_PATH
              value: "/auth"
            - name: KC_HOSTNAME_URL
              value: "https://keycloak.hazelsoft.in/auth/"
            - name: KC_HOSTNAME_ADMIN_URL
              value: "https://keycloak.hazelsoft.in/auth/"
            - name: KC_DB
              value: "postgres"
            - name: KC_DB_URL
              value: "jdbc:postgresql://postgres-service.default.svc.cluster.local/keycloak"
            - name: KC_DB_URL_HOST
              value: "postgres-service.default.svc.cluster.local"
            - name: KC_DB_URL_PORT
              value: "5432"
            - name: KC_DB_URL_DATABASE
              value: "keycloak"
            - name: KC_DB_USERNAME
              value: "svcuser"
            - name: KC_DB_PASSWORD
              value: "postgres"
          ports:
            - name: http
              containerPort: 8080
          livenessProbe:
            httpGet:
              path: /auth/realms/master
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /auth/realms/master
              port: 8080
            initialDelaySeconds: 90
            periodSeconds: 3
