apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: keycloak-pvc
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: gce-storage-class
  resources:
    requests:
      storage: 250Mi
